### ISSUE TITLE
CI Integration

### ISSUE THREAD

**Issue by luizgustavoob** [scanapi/scanapi#359] opened 2021-04-20 15:15 UTC
Hi guys! First i'm sorry for my bad english.

I'm integrating the library into a CI and I would like to know if there is any way to force an error if any integration test fail. Is this possible? Thanks!

**Comment by camilamaia** [comment] 2021-04-22 14:30
Hi @luizgustavoob! Welcome! Which CI are you using? By default, it should break the job if any integration test fail.

**Comment by luizgustavoob** [comment] 2021-04-22 20:07
Hi @camilamaia. Humm interesting!

I'm using the Gitlab CI. Due to the version of Python in the runners (2.7 :cry:), i did the tests from docker container. My Dockerfile it's simple, like that:
```
FROM python:3.8
RUN pip install pip setuptools --upgrade
RUN pip install scanapi
COPY /path/to/spec.yml .
RUN scanapi run spec.yml -o report.html
```
So, during image build, the tests are executed. After that, i just copy the generated report, like that:
```
docker build --progress=plain --file=./path/to/Dockerfile .	
-mkdir -p coverage
docker create --name my-container my-image
docker cp my-container:/report.html ./coverage/report.html
```

Maybe is not the best way, but... kkk
I noticed that when a test fails, the image build is not completed:
```
Step 6/6 : RUN scanapi run scan_external.yml
 ---> Running in 30d4b472aa95
Loading file scan_external.yml
Writing documentation
Making request GET https://brasilapi.com.br/api/cnpj/v1/05337875000105
Making request GET https://brasilapi.com.br/api/cnpj/v1/00
Making request GET https://brasilapi.com.br/api/cnpj/v1/00000000000000
Making request GET https://brasilapi.com.br/api/banks/v1
Making request GET https://brasilapi.com.br/api/banks/v1/1
Making request GET https://brasilapi.com.br/api/banks/v1/INVALIDBANK
Making request GET https://brasilapi.com.br/api/feriados/v1/2021
Making request GET https://brasilapi.com.br/api/feriados/v1/1899
Making request GET https://brasilapi.com.br/api/ibge/uf/v1
Making request GET https://brasilapi.com.br/api/ibge/uf/v1/RO
Making request GET https://brasilapi.com.br/api/ibge/uf/v1/INVALIDUF
Making request GET https://brasilapi.com.br/api/ddd/v1/46
Making request GET https://brasilapi.com.br/api/ddd/v1/00
Making request GET https://brasilapi.com.br/api/cep/v1/88034132
Making request GET https://brasilapi.com.br/api/cep/v1/00000000

The documentation was generated successfully.
It is available at /scanapi-report.html
The command '/bin/sh -c scanapi run scan_external.yml -o report.html' returned a non-zero code: 1
make: *** [Makefile:107: scan-external] Erro 1
```

When all asserts be passed, the build is successfully complete.

This is normal? Or does this way I'm doing doesn't make sense?

**Comment by camilamaia** [comment] 2021-04-23 00:56
Hmm 🤔 got it. The problem is that every time a test fails, the exit code will be 1

https://github.com/scanapi/scanapi/blob/master/scanapi/session.py#L23

The build image should be a separated step. I am not used with the gitlab ci. This is how I implemented using circleci: https://speakerdeck.com/cmaiacd/57o-python-floripa-on-line-como-testar-e-documentar-rest-apis-com-scanapi?slide=33

**Comment by luizgustavoob** [comment] 2021-04-28 13:09
Ok, i get it. So I will try to implement it in another way. Thanks @camilamaia :grin:

**Comment by camilamaia** [comment] 2021-04-29 14:31
Great @luizgustavoob! I will close this issue, but if you need any help with this again, let me know here and I reopen it, ok? Or also if you want to share later how you did it work :) Thanks!!

**Closed by camilamaia** 2021-04-29 14:31 UTC
